[default.files]
"Windows/Microsoft.Powershell_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"Windows/Completions" = { target = "~/Documents/PowerShell/Completions/", type = "symbolic", recurse = false }

[nvim.files]
"config/nvim" = { target = "~/AppData/Local/nvim", type = "symbolic", recurse = false }

