[theme]
theme = "semi-native"

[icons]
icons = "material-nf"

[[block]]
block = "music"

[[block]]
block = "net"
format = " $icon   $ip  ($ssid, $frequency, $signal_strength)  ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " $layout "
[block.mappings]
"German (Neo, QWERTZ)" = "neoqwertz"
"US (intl)" = "us (intl), corne"

[[block]]
block = "load"
format = " $icon  $1m.eng(w:4) "

[[block]]
block = "disk_space"
info_type = "used"
warning = 80
alert = 90
format = " $icon  $percentage "
format_alt = " $icon  $used / $total ($percentage avail: $available) "

[[block]]
block = "cpu"
format = " $icon  $utilization "
format_alt = " $icon  $utilization $frequency  $barchart "

[[block]]
block = "temperature"

[[block]]
block = "memory"
format = " $icon  $mem_used.eng(prefix:Mi) / $mem_total.eng(prefix:Mi) ($mem_used_percents.eng(w:2)) "
format_alt = " $icon  $mem_used.eng(prefix:Mi) / $mem_total.eng(prefix:Mi) ($mem_used_percents.eng(w:2))  ( $icon_swap  $swap_free / $swap_total) "

[[block]]
block = "amd_gpu"
format = " $icon  $utilization "
format_alt = " $icon  MEM: $vram_used_percents ($vram_used/$vram_total) "
interval = 1

[[block]]
block = "backlight"
format = " $icon  $brightness "

[[block]]
block = "battery"
format = " $icon  $percentage ($time_remaining.dur(hms:true, min_unit:m)) "

[[block]]
block = "hueshift"
format = " $icon  $temperature "

[[block]]
block = "sound"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %b %F %X') "
interval = 1

[[block]]
block = "uptime"
format = " $icon  $uptime"

[[block]]
block = "notify"
driver = "swaync"
[[block.click]]
button = "right"
action = "toggle_paused"
[[block.click]]
button = "left"
action = "show"


[[block]]
block = "menu"
text = " \uf011 "
[[block.items]]
display = " -&gt;   Sleep   &lt;-"
cmd = "systemctl suspend"
[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;  Reboot   &lt;-"
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"

