# User-defined functions to be executed inside templates.
[helpers]

[default]
# 'depends': packages that also ge tenabled when this one gets enabled
depends = ["nvim", "starship"]

# .files is the mapping between the path of the file relative to
# the repository root and its location in the filesystem
# On Windows: '~' is 'C:\Users\<USERNAME>\'
[default.files]
"README.md" = ""
gitconfig = "~/.gitconfig"
"wezterm.lua" = { target = "~/.wezterm.lua", type = "template", if = '(is_executable "wezterm")' }

[nvim.files]
"config/nvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[idea.files]
ideavimrc = "~/.ideavimrc"

[sway.files]
"config/sway" = { target = "~/.config/sway", type = "symbolic", recurse = false }

[fish.files]
"config/fish/config.fish" = "~/.config/fish/config.fish"
"config/fish/completions/render.fish" = { target = "~/.config/fish/completions/render.fish", type = "symbolic", if = '(is_executable "render")' }
# "config/fish/completions/rustup.fish" = { target = "~/.config/fish/completions/rustup.fish", type = "symbolic", if = '(is_executable "rustup")' }

[starship.files]
"config/starship.toml" = { target = "~/.config/starship.toml", type="symbolic", if = '(is_executable "starship")'}

# variables are constants for templated files
[default.variables]

