# User-defined functions to be executed inside templates.
[helpers]
[linux]

[default]
# 'depends': packages that also ge tenabled when this one gets enabled
depends = ["git", "nvim", "starship", "foot", "tmux", "lazygit", "wezterm"]

# .files is the mapping between the path of the file relative to
# the repository root and its location in the filesystem
# On Windows: '~' is 'C:\Users\<USERNAME>\'
[default.files]
"README.md" = ""
"setup.sh" = ""

[git.files]
gitconfig = "~/.gitconfig"

[wezterm.files]
"wezterm.lua" = { target = "~/.wezterm.lua", type = "template", if = '(is_executable "wezterm")' }

[nvim.files]
"config/nvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[idea.files]
ideavimrc = "~/.ideavimrc"

####### Sway
[sway]
depends = ["swayosd", "swaylock", "bin", "rofi"]
[sway.files]
"config/sway" = { target = "~/.config/sway", type = "symbolic", recurse = false }

[swayosd.files]
"config/swayosd" = { target = "~/.config/swayosd", type = "symbolic", recurse = false }

[swaylock.files]
"config/swaylock/config" = "~/.config/swaylock/config"

[systemd]
depends = ["bin"]

[systemd.files]
"config/systemd" = { target = "~/.config/systemd", type = "symbolic", if = '(is_executable "systemctl")' }

[bin.files]
"bin" = "~/.local/bin"

[rofi.files]
"config/rofi" = "~/.config/rofi"
#######

[fish.files]
"config/fish/config.fish" = "~/.config/fish/config.fish"
"config/fish/completions/render.fish" = { target = "~/.config/fish/completions/render.fish", type = "symbolic", if = '(is_executable "render")' }
# "config/fish/completions/rustup.fish" = { target = "~/.config/fish/completions/rustup.fish", type = "symbolic", if = '(is_executable "rustup")' }

[starship.files]
"config/starship.toml" = { target = "~/.config/starship.toml", type="symbolic", if = '(is_executable "starship")'}

[foot.files]
"config/foot/foot.ini" = { target = "~/.config/foot/foot.ini", type="template", if = '(is_executable "foot")'}

[tmux.files]
"tmux.conf" = { target = "~/.tmux.conf", type="symbolic", if = '(is_executable "tmux")'}

[lazygit.files]
"config/lazygit/config.yml" = { target = "~/.config/lazygit/config.yml", type = "template", if = '(is_executable "lazygit")' }

[ghostty.files]
"config/ghostty" = { target = "~/.config/ghostty", type = "symbolic", recurse = false }

# variables are constants for templated files
[default.variables]

