# User-defined functions to be executed inside templates.
[helpers]

[default]
# 'depends': packages that also ge tenabled when this one gets enabled
depends = ["nvim"]

# .files is the mapping between the path of the file relative to
# the repository root and its location in the filesystem
# On Windows: '~' is 'C:\Users\<USERNAME>\'
[default.files]
"README.md" = ""
gitconfig = "~/.gitconfig"
"wezterm.lua" = "~/.wezterm.lua"

[nvim.files]
"config/nvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[idea.files]
ideavimrc = "~/.ideavimrc"

[sway.files]
"config/sway" = { target = "~/.config/sway", type = "symbolic", recurse = false }

# variables are constants for templated files
[default.variables]

