set $mode_open "\
open: \
 (a)i | \
 (b)tm | \
 (d)evdocs | \
 (f)irefox | \
 (l)ocalsend | \
 (m)indwtr | \
 (n)neovide | \
 (o)bsidian | \
 (q)alculate | \
 (s)earch | \
 (S)potify | \
 (W)eather | \
 (^w)eather radar | \
 (w)hatsapp | \
 (z)eal | \
"
# hint:  :'<,'>sort i

set $mode_ai "\
open ai: \
 (c)laude | \
 (d)uck.ai | \
 (g)emini | \
 (m)istral | \
 (o)penai ChatGPT | \
 (p)erplexity | \
"
mode --pango_markup $mode_ai {
    bindsym c mode "default", exec chromium --app=https://claude.ai --ozone-platform=wayland
    bindsym d mode "default", exec chromium --app=https://duck.ai --ozone-platform=wayland
    bindsym g mode "default", exec chromium --app=https://gemini.google.com --ozone-platform=wayland
    bindsym m mode "default", exec chromium --app=https://chat.mistral.ai --ozone-platform=wayland
    bindsym o mode "default", exec chromium --app=https://chatgpt.com --ozone-platform=wayland
    bindsym p mode "default", exec chromium --app=https://www.perplexity.ai --ozone-platform=wayland

    bindsym Escape mode "default"
    bindsym Return mode "default"
}

mode --pango_markup $mode_open {
    bindsym a mode $mode_ai
    bindsym b mode "default", exec $term -e btm
    bindsym d mode "default", exec chromium --app=https://devdocs.io --ozone-platform=wayland
    bindsym f mode "default", exec firefox
    bindsym l mode "default", exec localsend
    bindsym m mode "default", exec mindwtr
    bindsym n mode "default", exec neovide
    bindsym o mode "default", exec obsidian
    bindsym q mode "default", exec qalculate-qt
    bindsym s mode "default", exec chromium --app=https://duckduckgo.com --ozone-platform=wayland
    bindsym Shift+s mode "default", exec spotify
    bindsym Shift+w mode "default", exec chromium --app=https://www.geosphere.at/de --ozone-platform=wayland
    bindsym Ctrl+w mode "default", exec chromium --app=https://portale.geosphere.at/ --ozone-platform=wayland
    bindsym w mode "default", exec chromium --app=https://web.whatsapp.com --ozone-platform=wayland
    bindsym z mode "default", exec zeal

    bindsym Escape mode "default"
    bindsym Return mode "default"
}

bindsym $mod+o mode $mode_open

# For duckduckgo (s)earch launching
for_window [app_id="chrome-duckduckgo.com__-Default"] floating enable, resize set 60ppt 60ppt

